---
# Organization to pull metrics from
organization: 'github-community-projects'

# Start date to pull metrics from
since: '2023-01-01'

# GitHub Pages path to the repository
# Used for handling relative paths for assets
basePath: '/org-metrics-dashboard'
